### PR TITLE
Add missing deps to publish release script.

### PR DESCRIPTION
**Pull request by mstechly**

### CODE REVIEW

**Comment by mstechly** [comment]
@max-radin I don't understand why, but it works now (see [this action](https://github.com/zapatacomputing/orquestra-core/actions/runs/2890160558)) :)

**Review by max-radin — COMMENTED** [review]
If I understand correctly, this PR changes the behavior so that the tests in `run_tests_before_release` get run using the main branch of the child repos (`orquestra-quantum` etc) instead of the versions specified in `setup.cfg`. Is that right? If so what would be the motivation for this change?

**Comment by mstechly** [comment]
@max-radin no, this PR changes the behavior, so that it runs using the versions specified in `setup.cfg`:
See this code:
```
run_tests_before_release:
	python3 -m venv ${VENV_NAME} && \
		${VENV_NAME}/bin/python3 -m pip install --upgrade pip && \
		${VENV_NAME}/bin/python3 -m pip install -e '.[dev]'
		${VENV_NAME}/bin/python3 -m pytest tests/
```
It doesn't install anything from the cloned repos, it installs it all from the correct versions.

I think what confuses you is that I added all those `checkout` actions back – for some reason it didn't work without them, but I don't remember why. Perhaps it was needed at some iteration of this code, but eventually it's actually not necessary.
I'll try removing them once again and seeing if it fails – when I look at the code right now I think they're actually unnecessary, it might have been some

**Comment by mstechly** [comment]
@max-radin Ok, please take a look again, it works (see [here](https://github.com/zapatacomputing/orquestra-core/runs/7920273273?check_suite_focus=true)) and I think it's cleaner now.
Good catch!

**Review by max-radin — APPROVED** [review]

**Pull request merged**
